// Auto-generated by LibreLane
module counter_8bit(
`ifdef USE_POWER_PINS
  inout VDD,
  inout VSS,
`endif
  input clk_i,
  input rst_ni,
  input en_i,
  output[7:0] count_o,
  output ovf_o
);
endmodule
