/* Generated by Yosys 0.62 (git sha1 7326bb7d6-dirty, x86_64-conda-linux-gnu-c++ 15.2.0 -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -fdebug-prefix-map=/tmp/really-long-path/conda/conda-bld/yosys_1778259432904/work=/usr/local/src/conda/yosys-0.62_0_g7326bb7d6 -fdebug-prefix-map=/home/windyphony/unic-cass/envs/librelane=/usr/local/src/conda-prefix -fPIC -O3) */

module counter_8bit(clk_i, rst_ni, en_i, count_o, ovf_o);
  input clk_i;
  wire clk_i;
  input rst_ni;
  wire rst_ni;
  input en_i;
  wire en_i;
  output [7:0] count_o;
  wire [7:0] count_o;
  output ovf_o;
  wire ovf_o;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _34_ (
    .I(count_o[7]),
    .ZN(_09_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _35_ (
    .I(count_o[6]),
    .ZN(_10_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _36_ (
    .I(count_o[5]),
    .ZN(_11_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _37_ (
    .I(count_o[4]),
    .ZN(_12_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _38_ (
    .I(count_o[3]),
    .ZN(_13_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _39_ (
    .I(count_o[2]),
    .ZN(_14_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _40_ (
    .I(rst_ni),
    .ZN(_15_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _41_ (
    .A1(en_i),
    .A2(rst_ni),
    .ZN(_16_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _42_ (
    .A1(count_o[0]),
    .A2(rst_ni),
    .ZN(_17_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _43_ (
    .A1(en_i),
    .A2(count_o[0]),
    .B1(_16_),
    .B2(_17_),
    .ZN(_00_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _44_ (
    .A1(en_i),
    .A2(count_o[0]),
    .B(count_o[1]),
    .ZN(_18_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _45_ (
    .A1(en_i),
    .A2(count_o[1]),
    .A3(count_o[0]),
    .ZN(_19_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _46_ (
    .A1(rst_ni),
    .A2(_19_),
    .ZN(_20_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _47_ (
    .A1(_18_),
    .A2(_20_),
    .ZN(_01_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and4_1 _48_ (
    .A1(en_i),
    .A2(count_o[2]),
    .A3(count_o[1]),
    .A4(count_o[0]),
    .Z(_21_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand4_1 _49_ (
    .A1(en_i),
    .A2(count_o[2]),
    .A3(count_o[1]),
    .A4(count_o[0]),
    .ZN(_22_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _50_ (
    .A1(rst_ni),
    .A2(_22_),
    .ZN(_23_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _51_ (
    .A1(_14_),
    .A2(_19_),
    .B(_23_),
    .ZN(_02_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _52_ (
    .A1(_13_),
    .A2(_22_),
    .B(rst_ni),
    .ZN(_24_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _53_ (
    .A1(_13_),
    .A2(_22_),
    .B(_24_),
    .ZN(_03_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _54_ (
    .A1(count_o[3]),
    .A2(_21_),
    .B(count_o[4]),
    .ZN(_25_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _55_ (
    .A1(_12_),
    .A2(_13_),
    .A3(_22_),
    .ZN(_26_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _56_ (
    .A1(_15_),
    .A2(_25_),
    .A3(_26_),
    .ZN(_04_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai31_1 _57_ (
    .A1(_12_),
    .A2(_13_),
    .A3(_22_),
    .B(_11_),
    .ZN(_27_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand4_1 _58_ (
    .A1(count_o[5]),
    .A2(count_o[4]),
    .A3(count_o[3]),
    .A4(_21_),
    .ZN(_28_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and3_1 _59_ (
    .A1(rst_ni),
    .A2(_27_),
    .A3(_28_),
    .Z(_05_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _60_ (
    .A1(count_o[6]),
    .A2(count_o[5]),
    .A3(count_o[4]),
    .ZN(_29_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _61_ (
    .A1(_13_),
    .A2(_22_),
    .A3(_29_),
    .ZN(_30_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi211_1 _62_ (
    .A1(_10_),
    .A2(_28_),
    .B(_30_),
    .C(_15_),
    .ZN(_06_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai31_1 _63_ (
    .A1(_13_),
    .A2(_22_),
    .A3(_29_),
    .B(_09_),
    .ZN(_31_)
  );
  gf180mcu_fd_sc_mcu7t5v0__or4_1 _64_ (
    .A1(_09_),
    .A2(_13_),
    .A3(_22_),
    .A4(_29_),
    .Z(_32_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and3_1 _65_ (
    .A1(rst_ni),
    .A2(_31_),
    .A3(_32_),
    .Z(_07_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _66_ (
    .A1(ovf_o),
    .A2(_16_),
    .ZN(_33_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _67_ (
    .A1(_15_),
    .A2(_32_),
    .B(_33_),
    .ZN(_08_)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _68_ (
    .CLK(clk_i),
    .D(_00_),
    .Q(count_o[0])
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _69_ (
    .CLK(clk_i),
    .D(_01_),
    .Q(count_o[1])
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _70_ (
    .CLK(clk_i),
    .D(_02_),
    .Q(count_o[2])
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _71_ (
    .CLK(clk_i),
    .D(_03_),
    .Q(count_o[3])
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _72_ (
    .CLK(clk_i),
    .D(_04_),
    .Q(count_o[4])
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _73_ (
    .CLK(clk_i),
    .D(_05_),
    .Q(count_o[5])
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _74_ (
    .CLK(clk_i),
    .D(_06_),
    .Q(count_o[6])
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _75_ (
    .CLK(clk_i),
    .D(_07_),
    .Q(count_o[7])
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _76_ (
    .CLK(clk_i),
    .D(_08_),
    .Q(ovf_o)
  );
endmodule
